name: 'telegram_client_linux'
description: 'Telegram Client Lightweight, blazing and Highly customizable for make application telegram based tdlib, mtproto, or bot api and support server side.'
version: '0.7.6'
homepage: 'https://github.com/azkadev/telegram_client'
repository: 'https://github.com/azkadev/telegram_client'
issue_tracker: 'https://github.com/azkadev/telegram_client/issues'
documentation: 'https://github.com/azkadev/telegram_client/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
false_secrets: 
  - 'linux/tdlib/'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'
dependencies: 
  flutter: 
    sdk: 'flutter'
dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'
  flutter_lints: '^2.0.0'
flutter: 
  plugin: 
    platforms: 
      linux: 
        ffiPlugin: true
