name: 'telegram_client'
description: 'Telegram Client Lightweight, blazing and Highly customizable for make application telegram based tdlib, mtproto, or bot api and support server side.'
version: '0.7.7'
repository: 'https://github.com/azkadev/telegram_client'
homepage: 'https://github.com/azkadev/telegram_client'
issue_tracker: 'https://github.com/azkadev/telegram_client/issues'
documentation: 'https://github.com/azkadev/telegram_client/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '^3.2.3'
dependencies: 
  general_lib: '^0.0.27'
  mason_logger: '^0.2.11'
  packagex: '^0.0.38'
  path: '^1.9.0'
  universal_io: '^2.2.2'
  yaml: '^3.1.2'
  yaml_edit: '^2.2.0'
  yaml_writer: '^2.0.0'
dev_dependencies: 
  lints: '^2.1.0'
  test: '^1.24.0'
topics: 
  - 'telegram'
  - 'tdlib'
  - 'mtproto'
  - 'userbot'
  - 'bot'
